name = "arch-script-redirector"
main = "worker.js"
compatibility_date = "2024-01-01"

routes = [{ pattern = "arch.sycamore.icu", zone_name = "sycamore.icu" }]

[[rules]]
type = "Text"
globs = ["*.sh"]
fallthrough = true
