name = "sycamore-arch-setup"
main = "worker.js"
compatibility_date = "2025-12-24"

routes = [{ pattern = "arch.sycamore.icu", zone_name = "sycamore.icu" }]

[[rules]]
type = "Text"
globs = ["*.sh"]
fallthrough = true
