name = "arch-setup"
main = "worker.js"
compatibility_date = "2025-12-24"

# 路由配置
routes = [{ pattern = "arch.sycamore.icu", custom_domain = true }]

[assets]
directory = "./public"
binding = "ASSETS"     # 在代码中通过 env.ASSETS 访问
